spring:
  config:
    import: classpath:config/config.properties
  application:
    name: spring-security-name
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security-demo
    username: root
    password: Nghia
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION}
      issuer: ${JWT_ISSUER}